app/usercustom/urls.py
"""
    Definición de las URI's para la aplicación main
"""
# Django Libraries
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

# Local Folders Libraries
from .views import (
    ActivateView,
    AvatarUpdateView,
    ChangePasswordView,
    LogOutModalView,
    PasswordRecoveryView,
    ProfileView,
    SignUpView,
)

app_name = "usercustom"

urlpatterns = [
    path("signup", SignUpView.as_view(), name="signup"),
    path("activate/<uidb64>/<token>", ActivateView.as_view(), name="activar"),
    path(
        "login/",
        LoginView.as_view(
            template_name="usercustom/login.html", redirect_field_name="next",
        ),
        name="login",
    ),
    path("logout", LogoutView.as_view(next_page="usercustom:login"), name="logout"),
    path("logoutmodal/", LogOutModalView.as_view(), name="logout-modal"),
    path("profile", login_required(ProfileView.as_view()), name="profile"),
    path("changepasword", login_required(ChangePasswordView), name="change-password"),
    path("password-recovery", PasswordRecoveryView.as_view(), name="password-recovery"),
    path(
        "password-recovery/<uidb64>/<token>",
        PasswordRecoveryView.as_view(),
        name="password-set",
    ),
    path("avatar", login_required(AvatarUpdateView.as_view()), name="avatar"),
]

sportbettingtips/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.utils.translation import gettext_lazy as _
from django.views.static import serve
# Thirdparty Libraries
from app.usercustom.views import ActivateLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.main.urls")),
    path("", include("app.usercustom.urls")),
    path("config", include("app.config.urls")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("static/<path:path>", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "<language_code>/language/activate/",
        ActivateLanguageView.as_view(),
        name="activate_language",
    ),
)

handler404 = "app.usercustom.views.error_404"
handler500 = "app.usercustom.views.error_500"

app/main/models/dpt.py
"""
Modelo de datos de la app main
"""
# Future Libraries
from __future__ import unicode_literals

# Django Libraries
from django.db import models


# ==================================================================================== #
class Dpt(models.Model):
    """Modelo que sirve para gestionar las dicisiones político  territoriales
    de los paises del mundo.
    """

    division = models.CharField(max_length=255, blank=True, null=True)
    nombre = models.CharField(max_length=255, blank=True, null=True)
    division_padre = models.ForeignKey(
        "self", on_delete=models.PROTECT, blank=True, null=True
    )
    arbol = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "División político territorial"
        verbose_name_plural = "División político territorial"

app/main/models/glosary.py
"""
Modelo de datos de la app main
"""
# Django Libraries
from django.db import models
from django.utils.translation import gettext_lazy as _

# Thirdparty Libraries
from ckeditor.fields import RichTextField
from simple_history.models import HistoricalRecords


# ==================================================================================== #
class Glosary(models.Model):
    """
    Modelo administrativo: Almacena la definición de los terminos utilizados en
    FincaSoft
    """

    history = HistoricalRecords()
    term = models.CharField(max_length=255, verbose_name=_("Term"))
    description = RichTextField(verbose_name=_("Description"))

    def __str__(self):
        return self.term

    class Meta:
        verbose_name = _("Term")
        verbose_name_plural = _("Glosary")

app/main/models/sequence.py
# Django Libraries
from django.db import models
from django.utils.translation import gettext_lazy as _

# Thirdparty Libraries
from simple_history.models import HistoricalRecords


class Sequence(models.Model):
    history = HistoricalRecords()
    name = models.CharField(verbose_name=_("name"), max_length=100, unique=True)
    prefix = models.CharField(_("Prefix"), max_length=40, default="default")
    padding = models.PositiveIntegerField(verbose_name=_("padding"), default=4)
    initial = models.PositiveIntegerField(verbose_name=_("initial"), default=1)
    increment = models.PositiveIntegerField(verbose_name=_("increment"), default=1)
    reset = models.PositiveIntegerField(verbose_name=_("reset"), null=True, blank=True)
    last = models.PositiveIntegerField(verbose_name=_("Last"), editable=False)
    next_val = models.PositiveIntegerField(verbose_name=_("Next"))

    class Meta:
        verbose_name = _("sequence")
        verbose_name_plural = _("sequences")

    def __str__(self):
        return "name={}, prefix={}, last={}".format(
            repr(self.name), repr(self.prefix), repr(self.last)
        )

app/main/forms.py
# -*- coding: utf-8 -*-
"""
Formularios para la app main
"""
# Django Libraries
from django.contrib.auth.forms import UserCreationForm
from django.forms import EmailInput, TextInput

# Own Libraries
from main.models import Persona
from usercustom.models import UserCustom


class PersonaCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UserCustom
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
        )
        widgets = {
            "first_name": TextInput(
                attrs={"class": "form-control", "placeholder": "Primer nombre"}
            ),
            "last_name": TextInput(
                attrs={"class": "form-control", "placeholder": "Primer apellido"}
            ),
            "username": TextInput(
                attrs={"class": "form-control", "placeholder": "Usuario"}
            ),
            "email": EmailInput(
                attrs={"class": "form-control", "placeholder": "Coreo electrónico"}
            ),
        }

app/main/views/dpt.py
""" Territorial Political Division Views
"""
# main.py

# Thirdparty Libraries
from dal import autocomplete

# Local Folders Libraries
from ..models import Dpt


# ==================================================================================== #
class EstadoAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para los estado  del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):
        queryset = Dpt.objects.filter(arbol="root.243")

        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)

        return queryset


# ==================================================================================== #
class MunicipioAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para los municipios del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):
        estado = self.forwarded.get("estado", None)
        if estado:
            queryset = Dpt.objects.filter(
                arbol__startswith="root.243",
                division__icontains="Municipio",
                division_padre=estado,
            )
        else:
            queryset = Dpt.objects.filter(
                arbol__startswith="root.243", division__icontains="Municipio"
            )
        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)
        return queryset


# ==================================================================================== #
class ParroquiaAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para las parroquias del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):
        municipio = self.forwarded.get("municipio", None)
        if municipio:
            queryset = Dpt.objects.filter(
                arbol__startswith="root.243",
                division__icontains="Parroquia",
                division_padre=municipio,
            )
        else:
            queryset = Dpt.objects.filter(
                arbol__startswith="root.243", division__icontains="Parroquia"
            )
        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)
        return queryset

app/main/views/sequence.py
# Django Library
# Django Libraries
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import router, transaction
from django.utils.translation import gettext_lazy as _

# Thirdparty Libraries
from app.main.views import (
    MainCreateView,
    MainDeleteView,
    MainDetailView,
    MainListView,
    MainUpdateView,
)

# Local Folders Libraries
# Localfolder Library
from ..models import Sequence

OBJECT_LIST_FIELDS = [
    {"string": _("Name"), "field": "name"},
    {"string": _("Prefix"), "field": "prefix"},
    {"string": _("Padding"), "field": "padding"},
    {"string": _("Initial"), "field": "initial"},
    {"string": _("Increment"), "field": "increment"},
    {"string": _("Reset"), "field": "reset"},
    {"string": _("Next"), "field": "next_val"},
]

OBJECT_FORM_FIELDS = [
    "name",
    "prefix",
    "padding",
    "initial",
    "increment",
    "reset",
    "next_val",
]


class SequenceListView(LoginRequiredMixin, MainListView):
    model = Sequence
    template_name = "base/list.html"
    extra_context = {"fields": OBJECT_LIST_FIELDS}


class SequenceDetailView(LoginRequiredMixin, MainDetailView):
    model = Sequence
    template_name = "base/detail.html"
    extra_context = {"fields": OBJECT_LIST_FIELDS}


class SequenceCreateView(LoginRequiredMixin, MainCreateView):
    model = Sequence
    fields = OBJECT_FORM_FIELDS
    template_name = "base/form.html"


class SequenceUpdateView(LoginRequiredMixin, MainUpdateView):
    model = Sequence
    fields = OBJECT_FORM_FIELDS
    template_name = "base/form.html"


# ==================================================================================== #
class SequenceDeleteView(LoginRequiredMixin, MainDeleteView):
    model = Sequence
    success_url = "base:sequences"


# ==================================================================================== #
def get_next_value(
    name="default",
    prefix="default",
    padding=4,
    initial=1,
    increment=1,
    reset=None,
    *,
    nowait=False,
    using=None
):
    """
    Return the next value for a given sequence.
    """
    if reset is not None:
        assert initial < reset

    if using is None:
        using = router.db_for_write(Sequence)

    with transaction.atomic(using=using, savepoint=False):
        sequence, created = Sequence.objects.select_for_update(
            nowait=nowait
        ).get_or_create(
            name=name,
            defaults={
                "prefix": prefix,
                "padding": padding,
                "initial": initial,
                "increment": increment,
                "reset": reset,
                "last": initial,
                "next_val": initial + 1,
            },
        )
        if not created:
            if (sequence.last + 1) != sequence.next_val:
                sequence.last = sequence.next_val
            else:
                sequence.last += increment

            sequence.next_val = sequence.last + 1

            if reset is not None and sequence.last >= reset:
                sequence.last = initial

            sequence.save()
        return "{}{}".format(prefix, str(sequence.last).zfill(padding))

app/main/views/views.py
# Librerias Django
# Django Libraries
from django.db.models import Q
from django.http import HttpResponse
from django.template import loader

# Thirdparty Libraries
from dal import autocomplete

# Own Libraries
# Librerias desarrolladas por mi
from flock.models import Flock
from main.models import DivisionPoliticoTerritorial, Taxonomy


# ==================================================================================== #
class EstadoAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para los estado  del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):
        queryset = DivisionPoliticoTerritorial.objects.filter(arbol="root.243")

        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)

        return queryset


# ==================================================================================== #
class MunicipioAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para los municipios del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):

        estado = self.forwarded.get("estado", None)

        if estado:
            queryset = DivisionPoliticoTerritorial.objects.filter(
                arbol__startswith="root.243",
                division__icontains="Municipio",
                division_padre=estado,
            )
        else:
            queryset = DivisionPoliticoTerritorial.objects.filter(
                arbol__startswith="root.243", division__icontains="Municipio"
            )

        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)

        return queryset


# ==================================================================================== #
class ParroquiaAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para las parroquias del modelo
    DivisionPoliticoTerritorial
    """

    def get_queryset(self):

        municipio = self.forwarded.get("municipio", None)

        if municipio:
            queryset = DivisionPoliticoTerritorial.objects.filter(
                arbol__startswith="root.243",
                division__icontains="Parroquia",
                division_padre=municipio,
            )
        else:
            queryset = DivisionPoliticoTerritorial.objects.filter(
                arbol__startswith="root.243", division__icontains="Parroquia"
            )

        if self.q:
            queryset = queryset.filter(nombre__icontains=self.q)

        return queryset


# ==================================================================================== #
class SubEspecieAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para el modelo Taxonomy (sub especie)
    """

    def get_queryset(self):

        queryset = Taxonomy.objects.filter(clado=100).order_by("otro")

        if self.q:
            queryset = queryset.filter(otro__icontains=self.q)

        return queryset


# ==================================================================================== #
class GrupoRacialAutoComplete(autocomplete.Select2QuerySetView):
    """Servicio de auto completado para el modelo Taxonomy (grupo racial)
    """

    def get_queryset(self):

        print("Aqui voy: %s" % self.forwarded.get("clado_superior", None))
        clado_superior = self.forwarded.get("clado_superior", None)

        queryset = Taxonomy.objects.filter(
            clado=105, clado_superior=clado_superior
        ).order_by("otro")

        if self.q:
            queryset = queryset.filter(otro__icontains=self.q)

        return queryset

app/main/templates/main/main.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Title -->
  <title>{% block title %}{% endblock title %} {{ settings.PROJECT_NAME }} | {{ settings.SLOGAN }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block header %}
  <!-- Favicon -->
  <link rel="icon" href="{{ MEDIA_URL }}icon/favicon_white.png">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static '/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700">
  <!-- Theme Flags -->
  <link rel="stylesheet" href="{% static 'flag-icon-css-master/css/flag-icon.min.css' %}">
  <!-- Theme fincaSoft -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/fincasoft.css' %}"> -->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  {% endblock header %}
  {% block head %}
  {% endblock %}

  {% block headscripts %}
  <!-- Admin Libraries -->
  <script type="text/javascript" src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static '/admin/js/jquery.init.js' %}"></script>
  <script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>
  <script type="text/javascript" src="{% static '/admin/js/inlines.js' %}"></script>

  <!-- Bootstrap 4 -->
  <script src="{% static '/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- FastClick -->
  <script src="{% static '/plugins/fastclick/fastclick.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static '/dist/js/adminlte.min.js' %}"></script>
  <!-- Toastr -->
  <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  {% endblock headscripts %}
  {% block stylesheets %}
  {% endblock stylesheets %}
  <style>
    .toast {
      opacity: 1 !important;
    }

    #toast-container>div {
      opacity: 1 !important;
    }

    .img-size-24 {
      height: auto;
      width: 24px;
    }

    .label {
      cursor: pointer;
      padding: 0px;
    }

    .progress {
      display: none;
      margin-bottom: 1rem;
    }

    .img-container img {
      max-width: 100%;
    }

    .select2-container--default .select2-selection--multiple .select2-selection__choice {
      background-color: #195323 !important;
      margin-top: -2px;
      border: 1px solid #8ff394;
    }

    .select2-container .select2-search--inline .select2-search__field {
      margin-top: 0px;
    }

    .select2-container--default .select2-selection--multiple {
      background-color: #fff;
      border: 1px solid #8ff394;
      border-radius: 4px;
      height: calc(2.25rem + 2px);
      padding-top: 7px;
      padding-left: .375rem;
    }

    .select2-container--default .select2-selection--multiple .select2-selection__clear {
      cursor: pointer;
      float: right;
      font-weight: bold;
      margin-top: 0px;
      margin-right: 15px;
    }

    .select2-container--default .select2-selection--single {
      background-color: #fff;
      border: 1px solid #8ff394;
      border-radius: 4px;
      height: calc(2.25rem + 2px);
      padding-top: 7px;
      padding-left: .375rem;
    }

    .select2-container--default .select2-selection--single .select2-selection__arrow b {
      border-color: #888 transparent transparent transparent;
      border-style: solid;
      border-width: 5px 4px 0 4px;
      top: 75%;
    }

    .row-striped:nth-of-type(odd) {
      background-color: #efefef;
    }

    .row-striped:nth-of-type(even) {
      background-color: #ffffff;
    }

    .page-item.active .page-link {
      z-index: 1;
      color: #fff;
      background-color: #195323;
      border-color: #195323;
    }

    .sidebar-dark-primary .nav-sidebar>.nav-item>.nav-link.active,
    .sidebar-light-primary .nav-sidebar>.nav-item>.nav-link.active {
      background-color: #195323;
      color: #fff;
    }

    input[required],
    input[required]:focus {
      background-color: #eee0f6;
    }

    .nav-tabs .nav-item.show .nav-link,
    .nav-tabs .nav-link.active {
      color: #495057;
      background-color: #fff;
      border-color: transparent #dee2e6 transparent;
      border-top: 3px solid #195323;
    }

    .add-row,
    .delete-row .fa-trash {
      color: #195323;
      cursor: pointer;
    }
  </style>
</head>

<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-dark navbar-secondary">
      <!--  -->
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <li>
          <div class="nav-link">
            <a href="#" class="nav-brand"><span
                class="logo-prefix">{{ settings.PREFIX }}</span><span class="logo-sufix">{{ settings.SUFIX }}</span></a>
          </div>
        </li>
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#"><i
              class="fas fa-globe"></i>&nbsp;{{ _('Language') }}&nbsp;<i class="fas fa-caret-down"></i></a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            {% for language_code, language in LANGUAGES %}
            {% if LANGUAGE_CODE != language_code %}
            <a class="dropdown-item" tabindex="-1" href="{% url 'activate_language' language_code %}"><span
                class="flag-icon flag-icon-{{ language_code }}"></span>&nbsp;{{ language }}</a>
            {% endif %}
            {% endfor %}
          </div>
        </li>&nbsp;
        <li class="nav-item dropdown">
          <style>
            .user-link img {
              height: auto;
              width: 2.1rem;
            }
          </style>
          {% if request.user.is_authenticated %}
          <a style="color:#fff;" role="button" data-toggle="dropdown" class="navbar-brand d-block user-link">
            <img src="{{ request.user.avatar.url }}" id="user_avatar" class="img-circle" alt="{{ request.user }}">
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'usercustom:profile' %}">{{ _('Profile') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"
              onclick="return abrir_modal('{% url 'usercustom:logout-modal' %}')">{{ _('Logout') }}</a>
          </div>
          {% endif %}
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Menú lateral -->
    {% block menu_lateral %}
    {% include "main/menu.html" %}
    {% endblock menu_lateral %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Main content -->
      {% block breadcrumbs %}
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          {% for btn in breadcrumbs %}
          {% if btn.url %}
          <li class="breadcrumb-item"><a href="{{ btn.url }}">{{ btn.name }}</a></li>
          {% else %}
          <li class="breadcrumb-item active" aria-current="page">{{ btn.name }}</li>
          {% endif %}
          {% endfor %}
        </ol>
      </nav>
      {% endblock breadcrumbs %}
      <section class="content">
        <!-- Contenido dinamico de cada página -->
        {% block content %}{% endblock content %}
      </section>
    </div>
    <!-- /.content-wrapper -->

    <footer class="enlace main-footer">
      <div class="float-right d-none d-sm-block"><b>{{ _('Version') }}</b> 1.25</div>
      <strong>Copyright &copy; {{ settings.YEA }}</strong> <a class="mylink" target="_blank"
        href="#"><b>{{ settings.PREFIX }}</b>{{ settings.SUFIX }}</a>. {{ _('All rights reserved.') }}
    </footer>

    <!-- Poup para los modales -->
    <div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-labelledby="genericModal"></div>
  </div>
  {% block javascripts %}
  {% endblock javascripts %}
  <!-- Page script -->
  <script>
    function abrir_modal(url) {
      $('#popup').load(url, function () {
        $(this).modal('show');
      });
      return false;
    }

    $(document).ready(function () {
      toastr.options.closeButton = true
      toastr.options.timeOut = 3000
      toastr.options.preventDuplicates = true
      toastr.options.progressBar = true

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            toastr.error("{{ error|escape }}")
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          toastr.error("{{ error|escape }}")
        {% endfor %}
      {% endif %}

      {% if next %}
        {% if request.user.is_authenticated %}
          toastr.warning("{{ _('Your account does not have the necessary privileges to access this section. To continue, log in with an account that has the necessary privileges.') }}")
        {% else %}
          toastr.info("{{ _('Please login to visit this page.') }}")
        {% endif %}
      {% endif %}


      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'debug' %}
            toastr.info("{{ message }}")
          {% endif %}
          {% if message.tags == 'info' %}
            toastr.info("{{ message }}")
          {% endif %}
          {% if message.tags == 'success' %}
            toastr.success("{{ message }}")
          {% endif %}
          {% if message.tags == 'warning' %}
            toastr.warning("{{ message }}")
          {% endif %}
          {% if message.tags == 'error' %}
            toastr.error("{{ message }}")
          {% endif %}
        {% endfor %}
      {% endif %}
    });
  </script>
</body>

</html>

app/main/templates/main/menu.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link">
    <img src="{% get_media_prefix %}icon/favicon_white.png" alt="{{ settings.PROJECT_NAME }} Logo"
      class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text logo-prefix">{{ settings.PREFIX }}</span><span
      class="brand-text logo-sufix">{{ settings.SUFIX }}</span>
  </a>
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <!-- <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            {% if request.user.is_authenticated %}
                <div class="image">
                    <a style="color:#fff;" href="{% url 'usercustom:profile' %}" class="d-block"><img src="{{ request.user.avatar.url }}" id="user_avatar" class="img-circle" alt="{{ request.user }}"></a>
                </div>
                <div class="info">
                    <a href="{% url 'usercustom:profile' %}" class="d-block">{{ user }}</a>
                </div>
            {% endif %}
        </div> -->
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
              with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-file-upload"></i>
            <p>{{ _("Production") }}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-clipboard-list"></i>
            <p>{{ _("Products") }}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-money-check-alt"></i>
            <p>{{ _("Budgets") }}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-file-upload"></i>
            <p>{{ _("Budgets") }}</p>
          </a>
        </li>
        {% if user.is_superuser %}
        {% include "rosetta/menu.html" %}
        {% include "config/menu.html" %}
        {% endif %}
        <!-- <li class="nav-header">LABELS</li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-circle text-danger"></i>
            <p class="text">Important</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-circle text-warning"></i>
            <p>Warning</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-circle text-info"></i>
            <p>Informational</p>
          </a>
        </li> -->
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>