app/usercustom/urls.py
"""
    Definición de las URI's para la aplicación main
"""
# Django Libraries
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

# Local Folders Libraries
from .views import (
    ActivateView,
    AvatarUpdateView,
    ChangePasswordView,
    LogOutModalView,
    PasswordRecoveryView,
    ProfileView,
    SignUpView,
)

app_name = "usercustom"

urlpatterns = [
    path("signup", SignUpView.as_view(), name="signup"),
    path("activate/<uidb64>/<token>", ActivateView.as_view(), name="activar"),
    path(
        "login/",
        LoginView.as_view(
            template_name="usercustom/login.html", redirect_field_name="next",
        ),
        name="login",
    ),
    path("logout", LogoutView.as_view(next_page="usercustom:login"), name="logout"),
    path("logoutmodal/", LogOutModalView.as_view(), name="logout-modal"),
    path("profile", login_required(ProfileView.as_view()), name="profile"),
    path("changepasword", login_required(ChangePasswordView), name="change-password"),
    path("password-recovery", PasswordRecoveryView.as_view(), name="password-recovery"),
    path(
        "password-recovery/<uidb64>/<token>",
        PasswordRecoveryView.as_view(),
        name="password-set",
    ),
    path("avatar", login_required(AvatarUpdateView.as_view()), name="avatar"),
]

sportbettingtips/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.utils.translation import gettext_lazy as _
from django.views.static import serve
# Thirdparty Libraries
from app.usercustom.views import ActivateLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.main.urls")),
    path("", include("app.usercustom.urls")),
    path("config", include("app.config.urls")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("static/<path:path>", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "<language_code>/language/activate/",
        ActivateLanguageView.as_view(),
        name="activate_language",
    ),
)

handler404 = "app.usercustom.views.error_404"
handler500 = "app.usercustom.views.error_500"

app/usercustom/models/models.py
import os

# Django Libraries
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
# Thirdparty Libraries
from simple_history.models import HistoricalRecords
# Local Folders Libraries
from ..sobre_escribir_imagen import SobreEscribirImagen

def image_path(instance, filename):
    return os.path.join("avatar", str(instance.pk) + "." + filename.rsplit(".", 1)[1])


class UserCustom(AbstractUser):
    """Modelo de los usuarios
    """

    TYPEUSER = (
        ("U", "USUARIO"),
        ("C", "CLIENTE"),
        ("A", "ASOCIADOS"),
    )
    history = HistoricalRecords()
    password = models.CharField(_("Password"), max_length=128)
    last_login = models.DateTimeField(_("Last login"), default=timezone.now)
    is_superuser = models.BooleanField(_("Super Admin"), default=False, db_index=True)
    is_staff = models.BooleanField(_("Staff"), default=False, db_index=True)
    is_active = models.BooleanField(_("Active"), default=False)
    username = models.CharField(
        _("User name"), max_length=150, db_index=True, unique=True
    )
    first_name = models.CharField(_("Name"), max_length=30)
    last_name = models.CharField(_("Last name"), max_length=30)
    email = models.CharField(
        _("Email"), max_length=254, null=False, db_index=True, unique=True
    )
    email_secundario = models.CharField(
        _("Secondary email"),
        max_length=254,
        null=True,
        blank=True,
        db_index=True,
        unique=True,
    )
    type_user = models.CharField(
        _("Type User."),
        max_length=1,
        choices=TYPEUSER,
        default=TYPEUSER[0][0],
        blank=True,
        null=True,
    )
    telefono = models.CharField(_("Phone"), max_length=255, blank=True, null=True)
    celular = models.CharField(_("Mobile Phone"), max_length=255, blank=True, null=True)
    fecha_nacimiento = models.DateField(_("Birthdate"), blank=True, null=True)
    sex = models.ForeignKey(
        "main.Sex",
        on_delete=models.PROTECT,
        verbose_name=_("Sex"),
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        max_length=255,
        storage=SobreEscribirImagen(),
        upload_to=image_path,
        blank=True,
        null=True,
        default="avatar/default_avatar.png",
    )

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_short_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        ordering = ["first_name", "last_name"]
        verbose_name = _("Person")
        verbose_name_plural = _("People")
        db_table = "auth_user"

app/usercustom/views/activate.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación main
"""

# Django Libraries
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView

# Thirdparty Libraries
from app.usercustom.tokens import ACCOUNT_ACTIVATION_TOKEN

# Local Folders Libraries
from ..models import UserCustom


# ==================================================================================== #
class ActivateView(RedirectView):
    """Esta clase activa a la persona cuando confirma el link enviado desde
    su correo
    """

    url = "usercustom:login"

    def get(self, request, *args, **kwargs):
        uidb64 = self.kwargs["uidb64"]
        token = self.kwargs["token"]
        url = self.get_redirect_url(*args, **kwargs)
        uid = force_str(urlsafe_base64_decode(uidb64))

        try:
            user = UserCustom.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserCustom.DoesNotExist):
            user = None

        token_valid = ACCOUNT_ACTIVATION_TOKEN.check_token(user, token)

        if user is not None and token_valid:
            user.is_active = True
            user.save()
            messages.success(
                self.request,
                _(
                    "Welcome, your account has been successfully activated. Please log in using your credentials."
                ),
            )
        else:
            messages.error(
                self.request,
                _(
                    "The sign up confirm link is invalid. If your account is not yet active, use the password recovery link."
                ),
            )

        return HttpResponseRedirect(reverse_lazy(url))

app/usercustom/views/activatelanguage.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación main
"""

# Standard Libraries
from urllib.parse import urlparse

# Django Libraries
from django.conf import settings
from django.shortcuts import redirect
from django.urls import resolve, reverse
from django.utils import translation
from django.views.generic.base import View
from django.shortcuts import render


# ==================================================================================== #
class ActivateLanguageView(View):
    """ Clase para la activación de un lenguaje
    """

    language_code = ""
    redirect_from = ""
    redirect_to = ""
    match = ""

    def get(self, request, *args, **kwargs):
        """ Metodo para hacer switch en idiomas
        """
        self.redirect_from = request.META.get("HTTP_REFERER", None) or "/"
        self.match = resolve(urlparse(self.redirect_from)[2])
        self.language_code = kwargs.get("language_code")
        if self.match.namespace:
            self.redirect_to = self.match.namespace + ":"
        self.redirect_to += self.match.url_name
        translation.activate(self.language_code)
        response = redirect(reverse(self.redirect_to, kwargs=self.match.kwargs))
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, self.language_code)
        return response
        

app/usercustom/views/avatar.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación main
"""
# Django Libraries
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

# Local Folders Libraries
from ..forms import AvatarForm
from ..models import UserCustom


# ==================================================================================== #
class AvatarUpdateView(UpdateView):
    """Vista para editarar las sale
    """

    model = UserCustom
    form_class = AvatarForm
    success_url = reverse_lazy("usercustom:profile")

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        # pk = self.kwargs.get(self.pk_url_kwarg)
        pk = self.request.user.pk
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        usuario = UserCustom.objects.get(pk=self.request.user.pk)

        if request.method == "POST":
            form = AvatarForm(self.request.POST, self.request.FILES, instance=usuario)
            if form.is_valid():
                form.save()

        return redirect("usercustom:profile")


# ==================================================================================== #
# def avatar(request):
#     """Función para actualizar el avatar
#     """

#     usuario = UserCustom.objects.get(pk=request.user.pk)

#     if request.method == 'POST':
#         form = AvatarForm(request.POST, request.FILES, instance=usuario)
#         if form.is_valid():
#             form.save()

# return redirect('usercustom:profile')

app/usercustom/views/logoutmodal.py
"""Sub Vista logout modaldel módulo erp
"""
# Django Libraries
from django.views.generic import TemplateView


# ==================================================================================== #
class LogOutModalView(TemplateView):
    """Lista de las ordenes de venta
    """

    template_name = "usercustom/logoutmodal.html"

app/usercustom/views/passwordchange.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación main
"""

# Django Libraries
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _


# ==================================================================================== #
def cambio_clave(request):
    """Esta función es para el cambio de clave del usuario
    """
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Importante!
            messages.success(
                request,
                _(
                    "Your password change was successfully \
                processed"
                ),
            )
            return redirect("usercustom:profile")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "usercustom/password_change_form.html", {"form": form})

app/usercustom/views/profile.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación main
"""

# Django Libraries
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

# Thirdparty Libraries
from app.usercustom.forms import AvatarForm, PerfilForm

# Local Folders Libraries
from ..models import UserCustom


# ==================================================================================== #
class ProfileView(SuccessMessageMixin, UpdateView):
    """Vista para editarar las sale
    """

    model = UserCustom
    form_class = PerfilForm
    template_name = "usercustom/profile.html"
    success_message = _("Your profile was updated successfully")
    success_url = reverse_lazy("usercustom:profile")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_avatar"] = AvatarForm(instance=self.request.user)

        return context

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        # pk = self.kwargs.get(self.pk_url_kwarg)
        pk = self.request.user.pk
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj

app/usercustom/views/views.py
from django.shortcuts import render

# Create your views here.

app/usercustom/templates/usercustom/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ settings.PROJECT_NAME }} | {{ _('Login') }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Favicon -->
  <link rel="icon" href="{{ MEDIA_URL }}icon/favicon_white.png">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ STATIC_URL }}plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Toastr -->
  <link rel="stylesheet" href="{{ STATIC_URL }}plugins/toastr/toastr.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ STATIC_URL }}dist/css/adminlte.min.css">
  <!-- <link rel="stylesheet" href="{{ STATIC_URL }}css/fincasoft.css"> -->
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Google Recaptcha -->
  <script src='https://www.google.com/recaptcha/api.js?hl={{ LANGUAGE_CODE }}'></script>


  <style>
    .toast {
      opacity: 1 !important;
    }

    #toast-container>div {
      opacity: 1 !important;
    }
  </style>
</head>

<body class="hold-transition django-font-w login-page django-background">
  <div class="login-box">
    <div class="login-logo">
      <a href="#" class="nav-brand">
        <h1 class="display-5"><span class="logo-prefix">{{ settings.PREFIX }}</span><span class="logo-sufix">{{settings.SUFIX }}</span></h1>
      </a>
    </div>
    <div class="card">
      <div class="card-body login-card-body">
        <div class="d-flex p-0">
          <ul class="nav nav-pills ml-auto">
            <li class="nav-item dropdown">
              <a style="color: #6c757d;" class="dropdown-toggle" data-toggle="dropdown" href="#">{{ _('Language') }}</a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for language_code, language in LANGUAGES %}
                {% if LANGUAGE_CODE != language_code %}
                <a class="dropdown-item" tabindex="-1" href="{% url 'activate_language' language_code %}">{{language_code}}{{ language }}</a>
                {% endif %}
                {% endfor %}
              </div>
            </li>
          </ul>
        </div><!-- /.card-header -->
        <p class="login-box-msg">{{ _('Log in') }}</p>
        <form method="POST">
          {% csrf_token %}
          {% if next != '' %}
          <input type="hidden" name="next" value="{{ next }}">
          {% endif %}
          <div class="input-group mb-3">
            <input type="text" class="form-control django-font-g" name="username" required id="id_username"
              placeholder="{{ _('User') }}">
            <div class="input-group-append">
              <div class="input-group-text"><span class="fas fa-user"></span></div>
            </div>
          </div>
          <div class="input-group mb-3">
            <input type="password" name="password" class="form-control django-font-g" required id="password"
              placeholder="{{ _('Password') }}">
            <div class="input-group-append">
              <div class="input-group-text"><span class="fas fa-lock"></span></div>
            </div>
          </div>
          <div class="row">
            <div class="enlace col-8">
              <a href="{% url 'usercustom:password-recovery' %}">{{ _('Password recovery') }}<br>
                <a href="{% url 'usercustom:signup' %}">{{ _('Signup') }}</a>
            </div>
            <!-- /.col -->
            <div class="col-4">
              <button type="submit" class="btn btn-fincasoft btn-block btn-flat">{{ _('Login') }}</button>
            </div>
            <!-- /.col -->
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- jQuery -->
  <script src="{{ STATIC_URL }}plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="{{ STATIC_URL }}plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Toastr -->
  <script src="{{ STATIC_URL }}plugins/toastr/toastr.min.js"></script>
  <!-- AdminLTE App -->
  <script src="{{ STATIC_URL }}dist/js/adminlte.min.js"></script>

</body>

</html>

app/usercustom/templates/usercustom/logoutmodal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ _('Are you sure you want to logout?') }}</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">{{ _('Select logout if you want to leave the session.') }}</div>
        <div class="modal-footer">
            <button class="btn btn-outline-secondary" type="button" data-dismiss="modal">{{ _('Cancel') }}</button>
            <a class="btn btn-outline-custom pull-left" href="{% url 'usercustom:logout' %}">{{ _('Logout') }}</a>
        </div>
    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->

app/usercustom/templates/usercustom/profile.html
{% extends "main/main.html" %}
{% load humanize static %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block header %}
<!-- Favicon -->
<link rel="icon" href="{{ MEDIA_URL }}icon/favicon_white.png">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static '/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Toastr -->
<link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static '/dist/css/adminlte.min.css' %}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- Theme Flags -->
<link rel="stylesheet" href="{% static 'flag-icon-css-master/css/flag-icon.min.css' %}">
<!-- Theme fincaSoft -->
<!-- <link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/fincasoft.css' %}"> -->
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">


<!-- jQuery -->
<script type="text/javascript" src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock header %}
{% block stylesheets %}
<!-- Cropper JS -->
<link rel="stylesheet" href="{% static 'css/cropper.css' %}">
<style>
  .label {
    cursor: pointer;
    padding: 0px;
  }

  .progress {
    display: none;
    margin-bottom: 1rem;
  }

  .img-container img {
    max-width: 100%;
  }

  .profile-user-img {
    border: 3px solid #8f38ba;
    margin: 0 auto;
    padding: 3px;
    width: 100px;
  }
</style>
{% endblock stylesheets %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <!-- Profile Image -->
      <div class="card card-outline">
        <div class="card-body box-profile">
          <div class="text-center">
            <label class="label" data-toggle="tooltip" title="Change your avatar">
              <img class="profile-user-img img-fluid img-circle" id="avatar_img" src="{{ request.user.avatar.url }}"
                alt="{{ request.user }}">
              <form method="post" enctype="multipart/form-data" action="{% url 'usercustom:avatar' %}" id="formUpload">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <input type="file" class="sr-only" id="id_avatar" name="avatar" accept="image/*">
              </form>
            </label>
          </div>
          <h3 class="profile-username text-center">{{ user }}</h3>
          <a href="{% url 'usercustom:change-password'  %}"
            class="btn btn-custom btn-block"><b>{{ _('Change Password') }}</b></a>
        </div><!-- /.card-body -->
      </div><!-- /.card -->
    </div><!-- /.col -->
    <div class="col-md-9">
      <!-- Profile Image -->
      <div class="card">
        <div class="card-body">
          <form class="form-horizontal" action="{% url 'usercustom:profile' %}" method="post" role="form">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {% if forloop.counter0|divisibleby:"2" or forloop.counter0 == 0 %}
            <div class="row">
              {%endif%}
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="id_first_name">{{ field.label }}</label>
                  {{ field }}
                </div>
                <!-- /.col -->
              </div>
              {% if forloop.counter|divisibleby:"2" %}
            </div>
            <!-- /.row -->
            {% elif forloop.last %}
            <div class="col-sm-6">
              <div class="form-group">
              </div>
              <!-- /.col -->
            </div>
        </div>
        <!-- /.row -->
        {%endif%}
        {% endfor %}
        <div class="row">
          <div class="col-sm-12">
            <button type="submit" class="btn btn-custom float-right">{{ _('Submit') }}</button>
          </div>
        </div>
        </form>
      </div><!-- /.card-body -->
    </div><!-- /.card -->
  </div><!-- /.col -->
</div><!-- /.row -->
</div><!-- /.container-fluid -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">{{ _('Crop the image') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="img-container"><img id="image" src="{{ request.user.avatar.url }}"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{{ _('Cancel') }}</button>
        <button type="button" class="btn btn-outline-custom" id="crop">{{ _('Crop') }}</button>
      </div>
    </div>
  </div>
</div><!-- /.modal -->
{% endblock content %}
{% block javascripts %}
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2-control').select2()
  })
</script>
<!-- cropper 4.0.0 -->
<script src="{% static 'js/cropper.js' %}"></script>
<!-- page script -->
<script type="text/javascript">
   // Script para cortar el avatar con crop.js
   window.addEventListener('DOMContentLoaded', function () {
    var avatar = document.getElementById('avatar_img');
    var user_avatar = document.getElementById('user_avatar');
    var image = document.getElementById('image');
    var input = document.getElementById('id_avatar');
    var $progress = $('.progress');
    var $progressBar = $('.progress-bar');
    var $alert = $('.alert');
    var $modal = $('#modal');
    var cropper;
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();

    $('[data-toggle="tooltip"]').tooltip();

    input.addEventListener('change', function (e) {
      var files = e.target.files;
      var done = function (url) {
        input.value = '';
        image.src = url;
        $alert.hide();
        $modal.modal('show');
      };
      var reader;
      var file;
      var url;

      if (files && files.length > 0) {
        file = files[0];

        if (URL) {
          done(URL.createObjectURL(file));
        } else if (FileReader) {
          reader = new FileReader();
          reader.onload = function (e) {
            done(reader.result);
          };
          reader.readAsDataURL(file);
        }
      }
    });

    $modal.on('shown.bs.modal', function () {
      cropper = new Cropper(image, {
        aspectRatio: 1,
        viewMode: 3,
      });
    }).on('hidden.bs.modal', function () {
      cropper.destroy();
      cropper = null;
    });

    document.getElementById('crop').addEventListener('click', function () {
      var initialAvatarURL;
      var canvas;

      $modal.modal('hide');

      if (cropper) {
        canvas = cropper.getCroppedCanvas({width: 160, height: 160,});
        initialAvatarURL = avatar.src;
        avatar.src = canvas.toDataURL(); //Altero el avatar del perfil
        user_avatar.src = canvas.toDataURL(); //Altero el avatar de la barra superior
        $progress.show();
        $alert.removeClass('alert-success alert-warning');
        canvas.toBlob(function (blob) {
          var formData = new FormData();

          formData.append('avatar', blob, 'avatar.jpg');
          $.ajax("{% url 'usercustom:avatar' %}", {
            method: 'POST',
            headers:{"X-CSRFToken": csrftoken},
            data: formData,
            processData: false,
            contentType: false,

            xhr: function () {
              var xhr = new XMLHttpRequest();
              xhr.upload.onprogress = function (e) {
                var percent = '0';
                var percentage = '0%';
                if (e.lengthComputable) {
                  percent = Math.round((e.loaded / e.total) * 100);
                  percentage = percent + '%';
                  $progressBar.width(percentage).attr('aria-valuenow', percent).text(percentage);
                }
              };
              return xhr;
            },

            success: function () {
            },

            error: function () {
              avatar.src = initialAvatarURL;
            },

            complete: function () {
              $progress.hide();
            },
          });
          return false;
        });
      }
    });
  });
</script>
{% endblock javascripts %}